version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - isstow-network

  backend:
    build:
      context: ./extracted_code
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://admin:password@mongo:27017/
      - MONGODB_DB_NAME=isstow
    networks:
      - isstow-network
    restart: always

  frontend:
    build:
      context: ./frontend-code
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - isstow-network
    restart: always

networks:
  isstow-network:
    driver: bridge

volumes:
  mongo_data: